import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    {
      type: 'category',
      label: 'PART 1: Blockchain & ZK',
      items: [
        'parts-1-history/Introduction',
        'parts-1-history/Ethereum-Execution-Model',
        'parts-1-history/Transition-to-zkVM',
        'parts-1-history/RISC-V',
        'parts-1-history/Is-RISC-V-zkVM-the-Endgame',
      ],
    },
    {
      type: 'category',
      label: 'PART 2: RISC-V zkVM',
      items: [
        'parts-2-risc-v-zkvm/risc-v-zkvm-architecture',
        'parts-2-risc-v-zkvm/optimization',
        'parts-2-risc-v-zkvm/zkvm-landscape',
        'parts-2-risc-v-zkvm/deep-dive-into-benchmark',
      ],
    },
    {
      type: 'category',
      label: 'PART 3: Real-Time Proving',
      items: [
        {
          type: 'category',
          label: 'Real-Time Proving',
          link: {
            type: 'doc',
            id: 'parts-3-real-time-proving/realtime-proving',
          },
          items: [
            'parts-3-real-time-proving/Risc-zero',
            'parts-3-real-time-proving/Snarkify',
            'parts-3-real-time-proving/sp1',
            'parts-3-real-time-proving/ZisK',
            'parts-3-real-time-proving/zkSync',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'PART 4: Prover Network',
      items: [
        'parts-4-prover-network/succinct-network',
        'parts-4-prover-network/boundless',
      ],
    },
    {
      type: 'category',
      label: 'PART 5: Use Cases',
      items: [
        'parts-5-use-cases/historical-and-multichain-storage-proofs',
        'parts-5-use-cases/ibc-eureka',
        'parts-5-use-cases/lido',
        'parts-5-use-cases/multichain-governance-aggregator',
        'parts-5-use-cases/one-more',
      ],
    },
    {
      type: 'category',
      label: 'Miscellaneous',
      items: [
        'miscellaneous/TinyRAM',
        'miscellaneous/FRI', 
        'miscellaneous/sp1-one-pager'
      ],
    },
  ],
};

export default sidebars;
